version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: broker-postgres
    restart: always
    environment:
      POSTGRES_DB: brokerApp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - broker_data:/var/lib/postgresql/data
volumes:
  broker_data:

networks:
  broker-net:
